# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# Stage > Jobs > Task (Steps)

jobs:
- job: Job1
  steps:
  - script: echo Hello Job1, world changed 1st time!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

 
- job: Job2
  dependsOn: Job1
  steps:
  - script: echo Hello Job2 , world changed 1st time!

- job: Job3
  dependsOn: Job2
  steps:
  - script: echo Hello Job3 , world changed 1st time!

- job: Job4
  dependsOn: Job3  
  steps:
  - script: echo Hello Job4 , world changed 1st time!
