# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  Jobs:
  - job: FirstJob
      steps:
      - bash: echo build FirstJob


- stage: Devdeploy
  Jobs:
    - job: FirstJob Devdeploy
        steps:
        - bash: echo build FirstJob

  
- stage: QAdeploy
  Jobs:
    - job: QAdeploy
        steps:
        - bash: echo build QAdeploy

  
- stage: Proddeploy
  Jobs:
    - job: Proddeploy
        steps:
        - bash: echo build Proddeploy
   



